#' @title print.openmusesampling: prints summary statistics of an openmusesampling object
#' 
#' @param x an object generated by the openmusesampling function
#' 
#' @export 
print.openmusesampling <- function(x){
  cat("Estimated means from", x$B, "samples of size", x$size, "\n")
  cat("\n")
  cat("--------------------------------------------------------------------------------------\n")
  cat("\n")
  cat("Sample mean of", paste0(x$variable, ":"), x$mean, "\n")
  cat("\n")
  cat("95% CI:", "[", x$CI[1], ",", x$CI[2], "] \n")
  cat("\n")
  cat("--------------------------------------------------------------------------------------\n")
  cat("\n")
  cat("Metropolis-Hastings Random-Walk acceptance rate of non-neighbours:", x$acceptance_rate)
}